- name: "Patrick"
  questions:
    number: 5
    start_index: "A"
    inverse_range: "1,2,3" # indexes start with 0
  answers:
    "никогда": 1
    "редко": 2
    "иногда": 3
    "часто": 4
    "всегда": 5
  scales:
    - name: "Scale 1"
      range: "1,3,5"
      method: "avg"
    - name: "Scale 2"
      range: "2,4"
      method: "sum"
